### ISSUE TITLE
[SC069]Create function add candidate

### ISSUE THREAD

**Issue by nuon-neourng** [pnc-virtual-company/2018-selection#105]
For this task we need to be able to add candidates into database and display data on table

**Comment by dakhen-sok** [comment]
I will be back to work on this task soon after I finish on access the URL. Anyways you all can assign yourself to work on this task too.because it has a little bit complexity with a foreign key on the database from another table when I am trying to insert the global grade.so solve this maybe I need to spend a little bit time to research and know which table should I insert first and resolve with the foreign key either.

**Comment by SopheakWEP** [comment]
Now I'm try to fix family profile

**Comment by dakhen-sok** [comment]
For this task, I already finish after pair work with sopheak. So now you all can test it.

**Comment by nuon-neourng** [comment]
now our form can add new candidate
