### ISSUE TITLE
[SC003] Validate layout Manage the list of NGOs #task 6

### ISSUE THREAD

**Issue by vuthypouk** [pnc-virtual-company/2018-selection#16]
please read and understand about the interface with the requirement  some point that you want to change

**Comment by dakhen-sok** [comment]
I think that for this layout it is good enough to be follow and develop.

**Comment by nuon-neourng** [comment]
I think for the gender it should be use radio button not the select option like that.

**Comment by CheaChan** [comment]
I think this process very good, but I just want to make sure about the form for adding NGO after we click on "Add NGO" it will replace the list of NGO pop up to form add NGO pop up.

**Comment by SopheakWEP** [comment]
about the form to add NGO from my idea, I think we no need to has the form to add new NGO. Because if they choose the other from selection option we have one form to specify the other NGO. So they can put the Other NGO and no need to add new NGO to selection option. But if the New NGO they are still usually used for every selection I think it is good too.

**Comment by dakhen-sok** [comment]
For my idea to add other NGOs It has 2 way one is pop up and other is drop other input with delete Icon then we can add the new one and save the lists.
